In [1]:
import numpy as np

In [2]:
a = list(range(1000000))

In [6]:
b = np.arange(1000000)

In [4]:
%timeit sum(a)

26.6 ms ± 221 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
%timeit np.sum(b)

482 µs ± 22.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
size = 1000
def python_solo():
    x = range(size)
    y = range(size)
    z = [x[i]+y[i] for i in range(len(x))]
    return z
    
def numpy_solo():
    x = np.arange(size)
    y = np.arange(size)
    z = x + y
    return z

In [10]:
%timeit python_solo()

347 µs ± 29.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
%timeit numpy_solo()

4.85 µs ± 294 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# -------------------------------------------------------------------------------------------

In [12]:
lista = [1,2,3,4]
type(lista)

list

In [13]:
a = np.array(lista)

In [14]:
a

array([1, 2, 3, 4])

In [15]:
type(a)

numpy.ndarray

# Index

In [16]:
a[0]

1

In [17]:
a[3]

4

In [18]:
a[2] = 10.4

In [19]:
a

array([ 1,  2, 10,  4])

In [20]:
a.fill(3)

In [21]:
a

array([3, 3, 3, 3])

In [22]:
a = np.array(lista,dtype="float")

In [23]:
a.dtype

dtype('float64')

In [24]:
a

array([1., 2., 3., 4.])

In [25]:
a[0] = 2

In [26]:
a

array([2., 2., 3., 4.])

In [27]:
a.fill(4.2313463)

In [28]:
a

array([4.2313463, 4.2313463, 4.2313463, 4.2313463])

In [30]:
a[0] = 2.3
a

array([2.3      , 4.2313463, 4.2313463, 4.2313463])

# Multidimensionales

In [33]:
c = np.array([[1,2.0,3],[4,5,6],[7,8,9],[10,11,12]],)
c

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [34]:
c.dtype

dtype('float64')

In [35]:
c.ndim

2

In [36]:
c.shape

(4, 3)

In [37]:
a.shape

(4,)

In [38]:
c.nbytes

96

In [39]:
c.itemsize

8

In [40]:
c.size

12

# Creaciones

In [41]:
d = np.array([[1,2.0,3],[4,5,6],[7,8,9],[10,11,12]],)
d

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [45]:
#np.arange(100,150,2)
n = np.arange(100)
n.ndim

1

In [47]:
np.arange(100).reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
np.arange(100,200,5).reshape(4,5)

array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

In [52]:
np.zeros(10,dtype='float').reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
np.zeros_like(n)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [56]:
np.identity(100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [58]:
np.eye(4, k=1, dtype='float')

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [64]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [65]:
np.logspace(0,1,5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [66]:
import pandas as pd

In [67]:
%matplotlib inline
pd.DataFrame(np.logspace(0,1,5))

0
0   1.000000
1   1.778279
2   3.162278
3   5.623413
4  10.000000

# Indexing y Slicing

In [68]:
import numpy as np

In [70]:
a = np.array([10,12,14,16,18])
a

array([10, 12, 14, 16, 18])

In [71]:
a[1:3]

array([12, 14])

In [72]:
a[-1]

18

In [73]:
j = np.arange(36).reshape(6,6)

In [74]:
j

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [76]:
#ROJO
j[:,2]

array([ 2,  8, 14, 20, 26, 32])

In [83]:
#ANARANJADO
j[0,3:5]

array([3, 4])

In [86]:
#AZUL
j[4:6,4:6]

array([[28, 29],
       [34, 35]])

In [89]:
#AZUL v2
j[-2:,-2:]

array([[28, 29],
       [34, 35]])

In [92]:
#CUADROS AZULES
j[2::2,::2]

array([[12, 14, 16],
       [24, 26, 28]])

In [93]:
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
#ROJO
x[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [108]:
#AMARILLO
x[-1:]

array([[20, 21, 22, 23, 24]])

In [122]:
#CUADROS AZULES
x[1::2,:3:2]

array([[ 5,  7],
       [15, 17]])

# ===============================================

## Fancy Indexing // Boolean Indexing

In [124]:
import numpy as np

In [126]:
a = np.arange(1,80,10)
a

array([ 1, 11, 21, 31, 41, 51, 61, 71])

In [127]:
a[[0,3,4]]

array([ 1, 31, 41])

In [128]:
indices = [1,3,4]
a[indices]

array([11, 31, 41])

In [129]:
# boolean indexing

In [131]:
mask = np.array([0,1,1,0,0,1,0,0], dtype=bool)
mask

array([False,  True,  True, False, False,  True, False, False])

In [132]:
a<3

array([ True, False, False, False, False, False, False, False])

In [134]:
mask = a < 20
mask

array([ True,  True, False, False, False, False, False, False])

In [135]:
a[mask]

array([ 1, 11])

In [138]:
mask3 = np.array([0,3,1,0,0,1,0,0])

In [139]:
a[mask3]

array([ 1, 31, 11,  1,  1, 11,  1,  1])

In [150]:
t = np.array([-3,1,-2,3,3,2,-22,2,-8])
t

array([ -3,   1,  -2,   3,   3,   2, -22,   2,  -8])

In [143]:
mask = t < 0
mask

array([ True, False,  True, False, False, False,  True, False,  True])

In [144]:
t[mask]

array([ -3,  -2, -22,  -8])

In [151]:
t[mask] = 0
t

array([0, 1, 0, 3, 3, 2, 0, 2, 0])

In [152]:
t = np.array([0,1,0,3,12,20,0,2,0])
t

array([ 0,  1,  0,  3, 12, 20,  0,  2,  0])

In [153]:
t >= 3

array([False, False, False,  True,  True,  True, False, False, False])

In [155]:
(t<15).all() and (t>=3).all()

False

In [157]:
#& (and) | (or) ^ (xor)
mask = (t<15) & (t>=3)
t[mask]

array([ 3, 12])

In [161]:
p = np.array([
    [i for i in range(6)],
    [i for i in range(10,16)],
    [i for i in range(20,26)],
    [i for i in range(30,36)],
    [i for i in range(40,46)],
    [i for i in range(50,56)]
])
p

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [165]:
#AMARILLO
rows = np.arange(5)
rows
cols = np.arange(1,6)
cols
p[rows,cols]

array([ 1, 12, 23, 34, 45])

In [167]:
#AMARILLO
p[np.eye(6,k=1)==1]

array([ 1, 12, 23, 34, 45])

In [170]:
#ROJO
mask = np.array([1,0,1,0,0,1],dtype=bool)
p[mask,2]

array([ 2, 22, 52])

In [171]:
#AZULES
p[3:,[1,2,-1]]

array([[31, 32, 35],
       [41, 42, 45],
       [51, 52, 55]])

In [174]:
q = np.arange(25).reshape(5,5)
q

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [178]:
q[np.eye(5,k=1)==1]

array([ 1,  7, 13, 19])

In [191]:
mask = ((q%3)==0)
q[mask]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

# PANDAS